#!/usr/bin/env python3
# -*- coding: utf-8 -*-

height = 1.58
weight = 80.5

bmi = weight/(height*2)
print (bmi)
if bmi > 32:
    print("您的体重严重肥胖")
elif bmi > 28:
    print("您的体重肥胖")
elif bmi > 25:
    print('您的体重过重')
elif bmi > 18.5:
    print('您的体重\"正常\"')
elif bmi < 18.5:
    print("您的体重\"过轻\"")
    pass
